export const ADD_SERVICE_SUCCESS = "ADD_SERVICE_SUCCESS";
export const ADD_SERVICE_FAIL = "ADD_SERVICE_FAIL";
export const ADD_SERVICE_LOADING = "ADD_SERVICE_LOADING";

export const GET_CURRENT_SERVICE_loading = "GET_CURRENT_SERVICE_LOADING";
export const GET_CURRENT_SERVICE_FAIL = "GET_CURRENT_SERVICE_FAIL";
export const GET_CURRENT_SERVICE_SUCCESS = "GET_CURRENT_SERVICE_SUCCESS";

export const UPLOAD_MULTIPLE_IMAGES_SUCCESS = "UPLOAD_MULTIPLE_IMAGES_SUCCESS";
export const UPLOAD_MULTIPLE_IMAGES_FAIL = "UPLOAD_MULTIPLE_IMAGES_FAIL";
export const UPLOAD_MULTIPLE_IMAGES_LOADING = "UPLOAD_MULTIPLE_IMAGES_LOADING";
