export const ADD_SERVICE_SUCCESS = "ADD_SERVICE_SUCCESS";
export const ADD_SERVICE_FAIL = "ADD_SERVICE_FAIL";
export const ADD_SERVICE_LOADING = "ADD_SERVICE_LOADING";

export const GET_CURRENT_SERVICE_loading = "GET_CURRENT_SERVICE_LOADING";
export const GET_CURRENT_SERVICE_FAIL = "GET_CURRENT_SERVICE_FAIL";
export const GET_CURRENT_SERVICE_SUCCESS = "GET_CURRENT_SERVICE_SUCCESS";

export const UPLOAD_MULTIPLE_IMAGES_SUCCESS = "UPLOAD_MULTIPLE_IMAGES_SUCCESS";
export const UPLOAD_MULTIPLE_IMAGES_FAIL = "UPLOAD_MULTIPLE_IMAGES_FAIL";
export const UPLOAD_MULTIPLE_IMAGES_LOADING = "UPLOAD_MULTIPLE_IMAGES_LOADING";

export const DELETE_IMAGE_LOADING = "DELETE_IMAGE_LOADING";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_FAIL = "DELETE_IMAGE_FAIL";

export const GET_ALL_SERVICES_LOADING = "GET_ALL_SERVICES_LOADING";
export const GET_ALL_SERVICES_SUCCESS = "GET_ALL_SERVICES_SUCCESS";
export const GET_ALL_SERVICES_FAIL = "GET_ALL_SERVICES_FAIL";

export const GET_USER_SERVICE_LOADING = "GET_USER_SERVICE_LOADING";
export const GET_USER_SERVICE_SUCCESS = "GET_USER_SERVICE_SUCCESS";
export const GET_USER_SERVICE_FAIL = "GET_USER_SERVICE_FAIL";

export const UPDATE_PROFESSION_LOADING = "UPDATE_PROFESSION_LOADING";
export const UPDATE_PROFESSION_SUCCESS = "UPDATE_PROFESSION_SUCCESS";
export const UPDATE_PROFESSION_FAIL = "UPDATE_PROFESSION_FAIL";
